// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGsL0R96A-FmGPOZJhGE8mFM6xlVIyzbY',
    appId: '1:966290974646:web:2bf1534ecc2a69b0914317',
    messagingSenderId: '966290974646',
    projectId: 'watch-hub-bcb42',
    authDomain: 'watch-hub-bcb42.firebaseapp.com',
    storageBucket: 'watch-hub-bcb42.firebasestorage.app',
    measurementId: 'G-MQWDZW2LV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3EkpC9of1z-ztz2JWgNty3n-TTj5C-UE',
    appId: '1:966290974646:android:66d8135780c280d7914317',
    messagingSenderId: '966290974646',
    projectId: 'watch-hub-bcb42',
    storageBucket: 'watch-hub-bcb42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBleDkj_FVsynpMIFbJZ9VIEbFDKnbNe6s',
    appId: '1:966290974646:ios:48e329604a734a50914317',
    messagingSenderId: '966290974646',
    projectId: 'watch-hub-bcb42',
    storageBucket: 'watch-hub-bcb42.firebasestorage.app',
    iosBundleId: 'com.example.premiumWatchApp',
  );
}
